# Generated by Django 4.2 on 2024-08-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_hashtag_article_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
