# Generated by Django 4.2 on 2024-08-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
